package com.mmproduction.abcd.carreminders;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.design.widget.NavigationView;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Gravity;
import android.view.Menu;
import android.view.MenuItem;


//class create so we can add the same draver to all activities
//!!all activities should imprement this class
//those activities should call onCreateDrawer
public class BaseActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {

    protected void onCreateDrawer(Bundle savedInstanceState) {
        //setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        //autogenerated
        final DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);

        // your other code...
        // setContentView(...) initialize drawer and stuff like that...

        // use thread for performance
        Thread t = new Thread(new Runnable() {

            @Override
            public void run() {

                SharedPreferences sp = getSharedPreferences("MyPrefs", Context.MODE_PRIVATE);
                boolean isFirstStart = sp.getBoolean("key", true);
                // we will not get a value  at first start, so true will be returned

                // if it was the first app start
                if(isFirstStart) {
                    drawer.openDrawer(Gravity.LEFT);
                    SharedPreferences.Editor e = sp.edit();
                    // we save the value "false", indicating that it is no longer the first appstart
                    e.putBoolean("key", false);
                    e.commit();
                }
            }
        });

        t.start();

    }

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            Intent intent = new Intent(getApplicationContext(), ViewSettingsActivity.class);
            startActivity(intent);
            finish();
        }

        return super.onOptionsItemSelected(item);
    }

    @SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {
        // Handle navigation view item clicks here.
        int id = item.getItemId();

        if (id == R.id.navAddNewCar) {
            Intent intent = new Intent(getApplicationContext(), MainActivity.class);
            startActivity(intent);
            finish();
        } else if (id == R.id.navViewYourCars) {
            Intent intent = new Intent(getApplicationContext(), ViewCarsActivity.class);
            startActivity(intent);
            finish();
        } else if (id == R.id.navViewEvents) {
            Intent intent = new Intent(getApplicationContext(), ViewEventsActivity.class);
            startActivity(intent);
            finish();
        } else if (id == R.id.navSettings) {
            Intent intent = new Intent(getApplicationContext(), ViewSettingsActivity.class);
            startActivity(intent);
            finish();
        } else if (id == R.id.navShare) {
            shareapp();

        } /*else if (id == R.id.navSend) {

        }*/

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }

    public void shareapp(){
        Intent sendIntent = new Intent();
        sendIntent.setAction(Intent.ACTION_SEND);
        sendIntent.putExtra(Intent.EXTRA_TEXT,
                R.string.sharing_string);
        sendIntent.setType("text/plain");
        startActivity(sendIntent);
    }



}
